package com.wafflestudio.csereal.core.academics.database

enum class AcademicsPostType {
    GUIDE, GENERAL_STUDIES_REQUIREMENTS, GENERAL_STUDIES_REQUIREMENTS_SUBJECT_CHANGES,
    CURRICULUM, DEGREE_REQUIREMENTS, DEGREE_REQUIREMENTS_YEAR_LIST, COURSE_CHANGES, SCHOLARSHIP;

    // GUIDE: 학부 안내
    // GENERAL_STUDIES_REQUIREMENTS: 필수 교양 과목
    // CURRICULUM: 전공 이수 표준 형태
    // DEGREE_REQUIREMENTS: 졸업 규정
    // COURSE_CHANGES: 교과목 변경 내역
    // SCHOLARSHIP: 장학 제도
}
