services:
  web:
    container_name: csereal_server_container
    build:
      context: ./
      args:
        PROFILE: ${PROFILE}
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://csereal_db_container:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - csereal_network
    image: ghcr.io/wafflestudio/csereal-server/server_image:main
  db:
    container_name: csereal_db_container
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - csereal_network
networks:
  csereal_network: