services:
  caddy:
    container_name: csereal_caddy
    image: caddy:2.7.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/certs:/certs
    environment:
      URL: ${URL}
      LOCAL_IP: ${LOCAL_IP}
      CERTIFICATE: ${CERTIFICATE}
      PRIVATE_KEY: ${PRIVATE_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
