services:
  db:
    env_file:
        - .env_db
    container_name: csereal_db_container
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./db_config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
