services:
    green:
        container_name: csereal_server_green
        ports:
            - 8080:8080
        volumes:
            - ./cse-files:/app/cse-files
            - ./files:/app/files

        environment:
            SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true"
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
            OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
            URL: ${URL}
            SLACK_TOKEN: ${SLACK_TOKEN}
            SLACK_CHANNEL: ${SLACK_CHANNEL}
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: always
        image: "ghcr.io/wafflestudio/csereal-server/server_image:${PROFILE}"
