spring:
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: index.html
  api-docs:
    path: /api-docs/json

---
spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/csereal
    username: root
    password: password
logging.level:
  default: INFO

---
spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
