spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          idsnucse:
            client-id: waffle-dev-local-testing
            client-secret: ${OIDC_CLIENT_SECRET_DEV}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/idsnucse
            scope: openid
        provider:
          idsnucse:
            issuer-uri: https://id-dev.bacchus.io/o
            jwk-set-uri: https://id-dev.bacchus.io/o/jwks

springdoc:
  swagger-ui:
    path: index.html
  api-docs:
    path: /api-docs/json

---
spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/csereal?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
logging.level:
  default: INFO

---
spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: create # TODO: change to validate (or none) when save actual data to server
    open-in-view: false
