spring:
    threads:
        virtual:
            enabled: false
    profiles:
        active: local
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 65
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: com.wafflestudio.csereal.common.config.MySQLDialectCustom
    servlet:
        multipart:
            enabled: true
            max-request-size: 100MB
            max-file-size: 100MB

server:
    tomcat:
        threads:
            max: 32
    servlet:
        session:
            timeout: 7200 # 2시간

springdoc:
    paths-to-match:
        - /api/**
    swagger-ui:
        path: index.html
    api-docs:
        path: /api-docs/json

csereal:
    upload:
        path: ./files/

oldFiles:
    path: ./cse-files/

endpoint:
    backend: http://localhost:8080/api
    frontend: http://localhost:3000

login-page: http://localhost:8080


logging:
    level:
        org:
            springframework:
                security: DEBUG
                web:
                    servlet: DEBUG

customlog:
    file:
        name: "csereal-backend"

---
spring:
    config.activate.on-profile: local
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/csereal?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
    security:
        oauth2:
            client:
                registration:
                    idsnucse:
                        client-id: cse-waffle-dev
                        client-secret: ${OIDC_CLIENT_SECRET_DEV}
                        authorization-grant-type: authorization_code
                        scope: openid, profile, email
                        redirect-uri: http://localhost:8080/api/v1/login/oauth2/code/idsnucse
                provider:
                    idsnucse:
                        issuer-uri: https://id.snucse.org/o
                        jwk-set-uri: https://id.snucse.org/o/jwks

customlog:
    file:
        base: "./logs"

---
spring:
    config.activate.on-profile: prod
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
    security:
        oauth2:
            client:
                registration:
                    idsnucse:
                        client-id: cse-waffle-prod
                        client-secret: ${OIDC_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        scope: openid, profile, email
                        redirect-uri: https://${URL}/api/v1/login/oauth2/code/idsnucse
                provider:
                    idsnucse:
                        issuer-uri: https://id.snucse.org/o
                        jwk-set-uri: https://id.snucse.org/o/jwks

csereal:
    upload:
        path: /app/files/

oldFiles:
    path: /app/cse-files/

endpoint:
    backend: https://${URL}/api
    frontend: https://${URL}

login-page: https://${URL}

slack:
    token: ${SLACK_TOKEN}
    channel: ${SLACK_CHANNEL}

customlog:
    file:
        base: "/app/logs"

---
spring:
    config.activate.on-profile: dev
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
    security:
        oauth2:
            client:
                registration:
                    idsnucse:
                        client-id: cse-waffle-dev
                        client-secret: ${OIDC_CLIENT_SECRET_DEV}
                        authorization-grant-type: authorization_code
                        scope: openid, profile, email
                        redirect-uri: https://${URL}/api/v1/login/oauth2/code/idsnucse
                provider:
                    idsnucse:
                        issuer-uri: https://id.snucse.org/o
                        jwk-set-uri: https://id.snucse.org/o/jwks

csereal:
    upload:
        path: /app/files/

oldFiles:
    path: /app/cse-files/

endpoint:
    backend: https://${URL}/api
    frontend: https://${URL}

login-page: https://${URL}

customlog:
    file:
        base: "./logs"
---
spring:
    config.activate.on-profile: test
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;
        username: sa
        password:
    jpa:
        database: h2
        database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
customlog:
    file:
        base: "./logs"
