name: Ktlint

on:
    pull_request:
        branches: [ develop ]

jobs:
    ktlint:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 21
                    distribution: 'temurin'
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: ktlintCheck with Gradle
                run: ./gradlew ktlintCheck
